server:
  port: 8888
  shutdown: graceful  # 배포 시 진행 중인 요청 완료 후 종료
  tomcat:
    accept-count: 100       # 커넥션 큐 사이즈 (스레드가 부족할 때 요청을 대기시키는 큐의 크기)
    max-connections: 200    # 최대 커넥션 수 (최대 TCP 커넥션 수 (클라이언트 연결 수))
    connection-timeout: 20000  # 커넥션 타임아웃 (ms)
    threads:
      max: 100 # 동시에 처리 가능한 요청 수 (커넥션 풀 40과 균형)
      min-spare: 20 # 기본 대기 스레드 수

spring:
  profiles:
    default: local
  application:
    name: spring-boot
  lifecycle:
    timeout-per-shutdown-phase: 30s  # Graceful shutdown 대기 시간


jwt:
  secret: kapanet_secret_key
  expiration:
    period: 86400000 # 24 * 60 * 60 * 1000 (하루)
    renew-before: 3600000 # 1 * 60 * 60 * 1000 (한시간)
